api: 
  ambiente-publicacao: LOCAL
  password: sr89787hom
  
#------ Spring -------------------------------------------------------------------------------------------
spring:         
  datasource:
    url: jdbc:postgresql://localhost:5432/soccer_db
    username: postgres
    password: 123456 

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
      hibernate.ddl-auto: update
      hibernate.temp.use_jdbc_metadata_defaults: false
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect

#  redis:
#    url: redis://localhost:6379
    
#    host: kuberneteshom.correios.com.br
#    port: 30845
#    password: ppmspwd
#    url: redis://localhost:6379
       
      
#------Logging --------------------------------------------------------------------------------------------------------------              
logging:
#  config: classpath:logback-spring.xml
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    com.betfair.api.soccer: DEBUG
    net.javacrumbs.shedlock: DEBUG
  file:
    name: soccer.log
    