api: 
  ambiente-publicacao: HOMOLOGACAO
  password: #<via kubernetes>
  #sr89787hom
  
  client:
    url-email: https://jhom2.correiosnet.int/mensagens/v1/emails
    url-preco: https://apihom.correios.com.br/preco
    url-idautorizacao-usuario: https://jhom2.correiosnet.int/idCorreiosWS-v1.2/idAutorizadorUsuario/idAutorizadorUsuarioService
    
#------ Spring ---------------------------------------------------------------------------------------------------
spring:    
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@scan-ac07.correiosnet.int:1521/ac07
    username: sarahom
    password: #<via kubernetes>
#    password: sr2005 
    hikari: 
      maximum-pool-size: 20
      pool-name: pool-sara
  
  cloud:
    consul:
      enabled: false
      host: consulhom-service.apimanagerhom
      port: 8500
      discovery: 
        prefer-ip-address: true 
        instanceId: ${api.service-id}
        serviceName: ${api.service-id}      
        health-check-critical-timeout: 168h # Apos 7 dias (check-critical) será removido o registro do CONSUL     

#  redis:
#    url: redis://sararedishom-service:6379   

  redis:
    host: redissaraatendimentohom-master-0.redissaraatendimentohom-headless
    port: 6379
    password: #<via kubernetes>
#    host: redis://redissaraatendimentohom-service:6379
 
#    sentinel:
#      master: mymaster
#      nodes: redissarahom-slave-0.redissarahom-headless:26379, redissarahom-slave-1.redissarahom-headless:26379 
#      nodes: redissarahom-slave-0.redissarahom-headless:26379
          
  rabbitmq:
    addresses: rabbitmqsarahom-0.rabbitmqsarahom-headless, rabbitmqsarahom-1.rabbitmqsarahom-headless
    port: 5672
    username: guest
    password: #<via kubernetes>
      
#------Logging --------------------------------------------------------------------------------------------------------------              
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    br.com.correios.api.sara-atendimento: DEBUG
  file:
    name: sara-atendimento.log